# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipeRater' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecipeRater
pod ‘Backendless’

  target 'RecipeRaterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
